### PR TITLE
typo in README.md

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Comment by oandreeva-nv** [comment]
Hi @JoanFM ,  thank you for fixing this! may I ask you to send us a CLA: https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla ?

**Review by oandreeva-nv — APPROVED** [review]
It was mentioned to me that this type of change may be merged without CLA, so leaving final decision to the contributor.

**Comment by amirhp110** [comment]
Hello,
My first time commenting on GitHub,
So excuse me on wrong people or place I am commenting on in advance.
In this README.md in the first step "Deploying a PyTorch Model" is mentioned to run "python export.py" but the docker does not have such file. Here is the command I used for the docker as suggested:
docker run -it --gpus all -v ${PWD}:/workspace nvcr.io/nvidia/pytorch:22.04-py3

Thanks in advance for your help,
Amir

**Comment by oandreeva-nv** [comment]
Hi @amirhp110 , make sure to run `docker run -it --gpus all -v ${PWD}:/workspace nvcr.io/nvidia/pytorch:22.04-py3` from the downloaded folder [`PyTorch`](https://github.com/triton-inference-server/tutorials/tree/main/Quick_Deploy/PyTorch). This folder contains `export.py`: https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/PyTorch/export.py

**Pull request merged**
